stages:
  - build

build:
  stage: build
  script:
    - |
      apt-get update && apt-get install --yes \
        build-essential \
        crossbuild-essential-arm64 \
        cmake \
        ninja-build \
        pkgconf \
        cdbs \
        devscripts \
        equivs \
        qemu-user-static \
        libcxxopts-dev
    - |
      dpkg --add-architecture arm64 \
      && apt-get update \
      && for arch in amd64 arm64; do \
        apt-get install --yes --no-install-recommends \
        pkgconf:${arch} \
        libsystemd-dev:${arch} \
        libspdlog-dev:${arch} \
        libgtest-dev:${arch}; \
      done \
      && rm -rf /var/lib/apt/lists/*

    # Build
    - INSIDE_CONTAINER=1 make amd64-debbuild
    - export DEB_BUILD_OPTIONS=nocheck
    - INSIDE_CONTAINER=1 make arm64-debbuild

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_BRANCH ==$CI_DEFAULT_BRANCH"

  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - "*.deb"
      - "*.changes"
      - "*.buildinfo"
