FROM debian:trixie

ARG DEBIAN_FRONTEND=noninteractive

ENV PIP_ROOT_USER_ACTION=ignore
ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
    build-essential \
    cdbs \
    devscripts \
    equivs \
    fakeroot \
    openssh-client \
    gcc-aarch64-linux-gnu \
    g++-aarch64-linux-gnu \
    libc6-dev-arm64-cross \
    cmake \
    curl \
    ninja-build \
    gdb-multiarch \
    gdb \
    git \
    wget \
    zsh \
    python3-pip \
    locales \
 && sed -i 's/^# *en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
 && locale-gen \
 && rm -rf /var/lib/apt/lists/*

RUN dpkg --add-architecture arm64 \
 && apt-get update \
 && for arch in amd64 arm64; do \
      apt-get install --yes --no-install-recommends \
        libsystemd-dev:${arch} \
        libspdlog-dev:${arch}; \
    done \
 && rm -rf /var/lib/apt/lists/*


RUN pip3 install --no-cache-dir --break-system-packages cmake-format

RUN ZSH="/root/.oh-my-zsh" RUNZSH=no CHSH=no \
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

ENTRYPOINT [ "/usr/bin/zsh" ]

