#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
(
    cd "${SCRIPT_DIR}/.."
    TARGETS=${@:-amd64-debbuild}
    echo "Running build in builder container for target(s): $TARGETS"
    podman-compose run --rm builder $TARGETS
)
