#!/bin/bash
set -euo pipefail

PORT=${1:-4242}             # Default gdbserver port
BUILD_TYPE=${2:-Debug}  

TOPDIR=$(git rev-parse --show-toplevel)
BUILD_DIR="$TOPDIR/sockact-example/build/amd64-$BUILD_TYPE/sockact-a"

echo "Start gdbserver with $PORT"
echo "Debug sockact-a from $BUILD_DIR"

sudo gdbserver --once ":$PORT" "$BUILD_DIR/sockact-a"
